feat: set admin hostname on web container as alternative dns
Innoactive/ansible-innoactive-portal-role pull request #109
Opened 2021-05-25 16:59 UTC by klyse

2021-05-25 17:18 UTC, burnedikt commented
Pretty sure the same also needs to happen for customization... Or in general any service that calls another one directly using its Hostname

2021-05-25 18:42 UTC, burnedikt approved these changes

2021-05-25 18:42 UTC, burnedikt commented on tasks/discovery_portal.yml
> +          - redis
```suggestion
```

Portal doesn't need to be accessible as `redis` I guess

2021-05-25 18:42 UTC, burnedikt commented on tasks/customization_service.yml
> +          - redis
```suggestion
```

Customization doesn't need to be accessible as redis I guess

2021-05-25 18:42 UTC, burnedikt requested changes
`-redis` shouldn't be an alias

2021-05-26 07:12 UTC, klyse commented
> `-redis` shouldn't be an alias

crap, that was a copy paste issue 😢

2021-05-26 08:45 UTC, burnedikt approved these changes

2021-05-26 13:27 UTC, merged